// Regnum Moravicum v2.1 - Initial State
// This file is a placeholder - initial state is generated by generators.ts
// But we export the constants here for reference

export const INITIAL_YEAR = 902;
export const INITIAL_TICK = 0;
export const MAX_TICKS = 576; // 48 years * 12 months

export const INITIAL_RULER_NAME = 'Mojmír II.';
export const INITIAL_DYNASTY_NAME = 'Mojmírovci';

export const INITIAL_RESOURCES = {
  gold: 1000,
  food: 100,
  wood: 50,
  stone: 50,
  iron: 30,
  prestige: 10
};

export const INITIAL_RELIGION = { value: 0 }; // Balanced between Rome and Constantinople

export const MORAVIAN_ZUPY = [
  'Nitra', 'Devín', 'Bratislava', 'Trnava', 'Zvolen',
  'Banská Bystrica', 'Košice', 'Prešov', 'Žilina', 'Poprad', 'Bardejov'
] as const;

// Kánon v1.1: Kumáni sú novou stepnou frakciou až od ~1090, nie sú prítomní pri
// štarte hry (902) - nahradení Bogatovcami, kánonickým vnútorným antagonistom.
export const INITIAL_FACTIONS = [
  { name: 'Župani', personality: 'loyal' as const },
  { name: 'Cyrilometodskí Kňazi', personality: 'opportunist' as const },
  { name: 'Byzantskí Poslovia', personality: 'opportunist' as const },
  { name: 'Nemeckí Kolonisti', personality: 'traitor' as const },
  { name: 'Maďarské zvyšky', personality: 'aggressive' as const },
  { name: 'Bogatovci', personality: 'opportunist' as const }
] as const;

export default {
  INITIAL_YEAR,
  INITIAL_TICK,
  MAX_TICKS,
  INITIAL_RULER_NAME,
  INITIAL_DYNASTY_NAME,
  INITIAL_RESOURCES,
  INITIAL_RELIGION,
  MORAVIAN_ZUPY,
  INITIAL_FACTIONS
};
